MyPython/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls import patterns, include, url
from login.views import *

urlpatterns = [
             url(r'^polls/', include('polls.urls')),
             url(r'^students/', include('students.urls')),
             url(r'^teachers/', include('teachers.urls')),
             url(r'^user/', include('login.urls')),
             url(r'^classes/', include('manage_classes.urls')),
             url(r'^admin/', admin.site.urls),
              url(r'^$',home),
              url(r'^logout/$', logout_page),
              url(r'^login/$',  'django.contrib.auth.views.login'),
              url(r'^accounts/login/$',
                  'django.contrib.auth.views.login'),  # If user is not login it will redirect to login page
              url(r'^register/$', register),
              url(r'^register/success/$', register_success),
              url(r'^home/$', home),
]

login/urls.py
from django.conf.urls import url
from . import views
app_name = 'login'
urlpatterns = [
    #url(r'^$',views.changepassword,name='changepassword'),
    #url(r'^(?s<student_id>[0-9]+)/$',views.detail,name="viewstudent"),
    #url(r'^(?P<student_id>[0-9]+)/edit/$',views.edit,name="editstudent"),
	#url(r'^(?P<student_id>[0-9]+)/update/$',views.update,name="updatestudent"),
	#url(r'^(?P<student_id>[0-9]+)/delete/$',views.delete,name="deletestudent"),
    url(r'^changepassword',views.changepassword,name="changepassword"),
    url(r'^changeprofile',views.changeprofile,name="changeprofile"),

]

manage_classes/urls.py
from django.conf.urls import url
from . import views
app_name = 'manage_classes'
urlpatterns = [
    url(r'^$',views.index,name='classes'),
    #url(r'^(?s<student_id>[0-9]+)/$',views.detail,name="viewstudent"),
    url(r'^(?P<class_id>[0-9]+)/edit/$',views.edit,name="editclass"),
	url(r'^(?P<class_id>[0-9]+)/update/$',views.update,name="updateclass"),
	url(r'^(?P<class_id>[0-9]+)/delete/$',views.delete,name="deleteclass"),
    url(r'^add',views.add,name="addclass"),

]

manage_classes/models.py
from __future__ import unicode_literals
import  datetime
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils import timezone
from django.contrib.auth.models import User

from django.db import models

# Create your models here.
class Classes(models.Model):
    class_name = models.CharField(max_length = 200)
    add_date = models.DateTimeField('date added')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.class_name




class Sections(models.Model):
    classs = models.ForeignKey(Classes,on_delete=models.CASCADE)
    section_name = models.CharField(max_length=200)
    add_date = models.DateTimeField('date added')

    def __str__(self):
        return self.section_name

manage_classes/forms.py
import re
from django import forms
from django.utils.translation import ugettext_lazy as _
class addclassform(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'required': True, 'max_length': 30}),label=_("Class Name"))
    

manage_classes/views.py
from django.shortcuts import render,get_object_or_404,render_to_response
from django.http import HttpResponse,Http404,HttpResponseRedirect
from django.template import loader
from django.core.urlresolvers import reverse
from .models import Classes,Sections
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.views.decorators.csrf import csrf_protect
from django.template import RequestContext
from manage_classes.forms import *
from django.utils import timezone
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.models import User

# Create your views here.
@login_required
def index(request):
	current_user = request.user
	uid = current_user.id
	class_list = Classes.objects.filter(user_id=uid).order_by('-id')
	paginator = Paginator(class_list, 30)
	page = request.GET.get('page')


	try:
		classes = paginator.page(page)
	except PageNotAnInteger:

		classes = paginator.page(1)
	except EmptyPage:

		classes = paginator.page(paginator.num_pages)
	return render(request, 'classes/index.html', {'classes':classes})
def edit(request,class_id):
    classs= get_object_or_404(Classes, id=class_id)
    return render(request, 'classes/editclass.html', {'classs': classs})
def update(request,class_id):
	classs = get_object_or_404(Classes, id=class_id)
	classs.class_name = request.POST['cname']
	classs.save()

	return HttpResponseRedirect(reverse('manage_classes:classes'))
@csrf_protect
def add(request):

    if request.method =='POST':
        form = addclassform(request.POST)
        variables = RequestContext(request, {'form': form})
        if form.is_valid():


            current_user = request.user
            user = User.objects.get(id=current_user.id)
            classs = Classes.objects.create(
            class_name = form.cleaned_data['name'],
            
			user_id = user.id,
            add_date =timezone.now(),
            )

            return HttpResponseRedirect(reverse('manage_classes:classes'))
    else:
        form = addclassform()
        variables = RequestContext(request,{'form':form})
    return render_to_response('classes/addclassform.html',variables)
def delete(request,class_id):
	classs = get_object_or_404(Classes, id=class_id)
	classs.delete()

	return HttpResponseRedirect(reverse('manage_classes:classes'))

manage_classes/templates/classes/addclassform.html
{% extends "base.html" %}


{% block content %}

    <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3>Add Class</h3>
              </div>

              <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                  <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                      <button class="btn btn-default" type="button">Go!</button>
                    </span>
                  </div>
                </div>
              </div>
            </div>
            <div class="clearfix"></div>
            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Add class </h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                          <li><a href="#">Settings 1</a>
                          </li>
                          <li><a href="#">Settings 2</a>
                          </li>
                        </ul>
                      </li>
                      <li><a class="close-link"><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
					{% if form.errors %}
					<div class="alert alert-danger">
					<p>Please check errors.</p>
					</div>
						
					{% endif %}
                  <div class="x_content">
                    <br />
					
						<form class="form-horizontal form-label-left" method="post" action="{% url 'manage_classes:addclass'%}">
						{% csrf_token %}
						<input type="hidden" name="user_id" value="{{ user.id }}">
						  <div class="form-group">
							<label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Class Name <span class="required">*</span>
							</label>
							<div class="col-md-6 col-sm-6 col-xs-12">
							  {{ form.name }}
							</div>
						  </div>
						  
						  <div class="ln_solid"></div>
						  <div class="form-group">
							<div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
							  <button type="submit" class="btn btn-success">Add</button>
							  <!--<input type="hidden" name="tid" value="{{teacher.id}}" />-->
							</div>
						  </div>

						</form>
					
                  </div>
                </div>
              </div>
            </div>

            
          </div>
        </div>
{% endblock %}

manage_classes/templates/classes/editclass.html
{% extends "base.html" %}


{% block content %}

    <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3>Edit Class</h3>
              </div>

              <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                  <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                      <button class="btn btn-default" type="button">Go!</button>
                    </span>
                  </div>
                </div>
              </div>
            </div>
            <div class="clearfix"></div>
            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Edit class </h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                          <li><a href="#">Settings 1</a>
                          </li>
                          <li><a href="#">Settings 2</a>
                          </li>
                        </ul>
                      </li>
                      <li><a class="close-link"><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <br />
					{% if classs %}
						
						{% if form.errors %}
							<p>Pls check.</p>
						{% endif %}
						<form class="form-horizontal form-label-left" method="post" action="{% url 'manage_classes:updateclass' classs.id %}">
						{% csrf_token %}
						  <div class="form-group">
							<label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Class Name <span class="required">*</span>
							</label>
							<div class="col-md-6 col-sm-6 col-xs-12">
							  <input type="text" id="first-name" required="required" class="form-control col-md-7 col-xs-12" name="cname" value="{{ classs.class_name }}">
							</div>
						  </div>
						  
						  <div class="ln_solid"></div>
						  <div class="form-group">
							<div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
							  <button type="submit" class="btn btn-success">Update</button>
							  
							</div>
						  </div>

						</form>
					{% endif %}
                  </div>
                </div>
              </div>
            </div>

            
          </div>
        </div>
{% endblock %}

manage_classes/templates/classes/index.html
{% extends "base.html" %}


{% block content %}
{% load staticfiles %}


    <!-- page content -->
        <div class="right_col" role="main">
          <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Class List </h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a aria-expanded="false" role="button" data-toggle="dropdown" class="dropdown-toggle" href="#"><i class="fa fa-wrench"></i></a>
                        <ul role="menu" class="dropdown-menu">
                          <li><a href="#">Settings 1</a>
                          </li>
                          <li><a href="#">Settings 2</a>
                          </li>
                        </ul>
                      </li>
                      <li><a class="close-link"><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>

                  <div class="x_content">

                   

                    <div class="table-responsive">
                      <table class="table table-striped jambo_table bulk_action">
                        <thead>
                          <tr class="headings">
                           
                            <th class="column-title">Class Name </th>
                            
                            
                            <th class="column-title no-link last"><span class="nobr">Action</span>
                            </th>
                            
                          </tr>
                        </thead>

                        <tbody>
						{% if classes %}
							{% for class in classes %}
							  <tr class="even pointer">
							   
								<td class=" ">{{ class.class_name }}</td>
								<td class=" last"><a href="{% url 'manage_classes:deleteclass' class.id %}" class="confirmation">Delete</a> | <a href="{% url 'manage_classes:editclass' class.id %}">Edit</a>
								
							  </tr>
						  {% endfor %}
                        {% else %}
							<tr class="even pointer">
							<td colspan="3">No class in List</td>
							</tr>
						{% endif %} 
                        </tbody>
                      </table>
                    </div>
					<div class="col-md-9 pagination">
						<span class="step-links">
							{% if classes.has_previous %}
								<a href="?page={{ classes.previous_page_number }}">previous</a>
							{% endif %}

							<span class="current">
								Page {{ classes.number }} of {{ classes.paginator.num_pages }}.
							</span>

							{% if classes.has_next %}
								<a href="?page={{ classes.next_page_number }}">next</a>
							{% endif %}
						</span>
					</div>
					<div class="col-md-3 right">
					<a href="{% url 'manage_classes:addclass'%}" class="btn btn-success right">Add Class</a>
					</div>
                  </div>
                </div>
              </div>
        </div>
        <!-- /page content -->
{% endblock %}