MyPython/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls import patterns, include, url
from login.views import *

urlpatterns = [
             url(r'^polls/', include('polls.urls')),
             url(r'^students/', include('students.urls')),
             url(r'^teachers/', include('teachers.urls')),
             url(r'^user/', include('login.urls')),
             url(r'^classes/', include('manage_classes.urls')),
             url(r'^admin/', admin.site.urls),
              url(r'^$',home),
              url(r'^logout/$', logout_page),
              url(r'^login/$',  'django.contrib.auth.views.login'),
              url(r'^accounts/login/$',
                  'django.contrib.auth.views.login'),  # If user is not login it will redirect to login page
              url(r'^register/$', register),
              url(r'^register/success/$', register_success),
              url(r'^home/$', home),
]

login/urls.py
from django.conf.urls import url
from . import views
app_name = 'login'
urlpatterns = [
    #url(r'^$',views.changepassword,name='changepassword'),
    #url(r'^(?s<student_id>[0-9]+)/$',views.detail,name="viewstudent"),
    #url(r'^(?P<student_id>[0-9]+)/edit/$',views.edit,name="editstudent"),
	#url(r'^(?P<student_id>[0-9]+)/update/$',views.update,name="updatestudent"),
	#url(r'^(?P<student_id>[0-9]+)/delete/$',views.delete,name="deletestudent"),
    url(r'^changepassword',views.changepassword,name="changepassword"),
    url(r'^changeprofile',views.changeprofile,name="changeprofile"),

]

students/urls.py
from django.conf.urls import url
from . import views
app_name = 'students'
urlpatterns = [
    url(r'^$',views.index,name='students'),
    #url(r'^(?s<student_id>[0-9]+)/$',views.detail,name="viewstudent"),
    url(r'^(?P<student_id>[0-9]+)/edit/$',views.edit,name="editstudent"),
	url(r'^(?P<student_id>[0-9]+)/update/$',views.update,name="updatestudent"),
	url(r'^(?P<student_id>[0-9]+)/delete/$',views.delete,name="deletestudent"),
    url(r'^add',views.add,name="addstudent"),
     
]

students/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
import  datetime
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils import timezone

# Create your models here.
class Students(models.Model):
    name = models.CharField(max_length=200)
    classs = models.IntegerField(max_length=11)
    add_date = models.DateTimeField('date added')
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    def __str__(self):
        return self.name

students/forms.py
import re
from django import forms
from django.utils.translation import ugettext_lazy as _
class addstudentform (forms.Form):
	 name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control','required':True,'max_length':30}), label=_("Name"))
	 classs=forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control','required':True,'max_length':30}), label=_("Class"))
	
	 #user_id = forms.IntegerField(widget=forms.HiddenInput)

students/views.py
from django.shortcuts import render,get_object_or_404,render_to_response
from django.http import HttpResponse,Http404,HttpResponseRedirect
from django.template import loader
from django.core.urlresolvers import reverse
from .models import Students

from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.views.decorators.csrf import csrf_protect
from django.template import RequestContext
from students.forms import *
from django.utils import timezone
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.models import User
from manage_classes.models import *

# Create your views here.
@login_required
def index(request):
    current_user  = request.user
    uid = current_user.id
    student_list = Students.objects.filter(user_id=uid).order_by('-id')
    paginator = Paginator(student_list, 30)
    page = request.GET.get('page')


    try:
        students = paginator.page(page)
    except PageNotAnInteger:

        students = paginator.page(1)
    except EmptyPage:

        students = paginator.page(paginator.num_pages)
    return render(request, 'students/index.html', {'students':students})




	

def delete(request,student_id):
	student = get_object_or_404(Students, id=student_id)
	student.delete()

	return HttpResponseRedirect(reverse('students:students'))
def edit(request,student_id):
    classes = Classes.objects.filter().order_by('-id')

    student = get_object_or_404(Students, id=student_id)
    return render(request, 'students/editstudent.html', {'student': student,'classes':classes})
def update(request,student_id):
	student = get_object_or_404(Students, id=student_id)
	student.name = request.POST['sname']
	student.classs= request.POST['classs']
	student.save()

	return HttpResponseRedirect(reverse('students:students'))

@csrf_protect
def add(request):
    classes = Classes.objects.filter().order_by('-id')
	
    if request.method =='POST':
        form = addstudentform(request.POST)
        if form.is_valid():
            current_user = request.user
            user = User.objects.get(id=current_user.id)
            student = Students.objects.create(
            name = form.cleaned_data['name'],
            classs  =form.cleaned_data['classs'],
			user_id = user.id,
            add_date =timezone.now(),
            )

            return HttpResponseRedirect(reverse('students:students'))
    else:
        form = addstudentform()
        variables = RequestContext(request,{'form':form,'classes':classes})
    return render_to_response('students/addstudentform.html',variables)

students/templates/students/addstudentform.html
{% extends "base.html" %}


{% block content %}

    <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3>Add Student</h3>
              </div>

              <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                  <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                      <button class="btn btn-default" type="button">Go!</button>
                    </span>
                  </div>
                </div>
              </div>
            </div>
            <div class="clearfix"></div>
            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Add student </h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                          <li><a href="#">Settings 1</a>
                          </li>
                          <li><a href="#">Settings 2</a>
                          </li>
                        </ul>
                      </li>
                      <li><a class="close-link"><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <br />
					
						<form class="form-horizontal form-label-left" method="post" action="{% url 'students:addstudent'%}">
						{% csrf_token %}
						<input type="hidden" name="user_id" value="{{ user.id }}">
						  <div class="form-group">
							<label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Student Name <span class="required">*</span>
							</label>
							<div class="col-md-6 col-sm-6 col-xs-12">
							  {{ form.name }}
							</div>
						  </div>
						  <div class="form-group">
							<label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Student Class <span class="required">*</span>
							</label>
							<div class="col-md-6 col-sm-6 col-xs-12">
							  <select name="classs" required class="form-control">
								<option>Select Class </option>
								{% if classes %}
									{% for cls in classes%}
										<option value="{{cls.id}}">{{cls.class_name}}</option>
									{% endfor %}
								{% endif %}
							  </select>
							</div>
						  </div>
						 
						  <div class="ln_solid"></div>
						  <div class="form-group">
							<div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
							  <button type="submit" class="btn btn-success">Add</button>
							  <input type="hidden" name="sid" value="{{student.id}}" />
							</div>
						  </div>

						</form>
					
                  </div>
                </div>
              </div>
            </div>

            
          </div>
        </div>
{% endblock %}

students/templates/students/editstudent.html
{% extends "base.html" %}


{% block content %}

    <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3>Edit Student</h3>
              </div>

              <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                  <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                      <button class="btn btn-default" type="button">Go!</button>
                    </span>
                  </div>
                </div>
              </div>
            </div>
            <div class="clearfix"></div>
            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Edit student </h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                          <li><a href="#">Settings 1</a>
                          </li>
                          <li><a href="#">Settings 2</a>
                          </li>
                        </ul>
                      </li>
                      <li><a class="close-link"><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <br />
					{% if student %}
						{% if form.errors %}
							<p>Pls check.</p>
						{% endif %}
						<form class="form-horizontal form-label-left" method="post" action="{% url 'students:updatestudent' student.id %}">
						{% csrf_token %}
						  <div class="form-group">
							<label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Student Name <span class="required">*</span>
							</label>
							<div class="col-md-6 col-sm-6 col-xs-12">
							  <input type="text" id="first-name" required="required" class="form-control col-md-7 col-xs-12" name="sname" value="{{ student.name }}">
							</div>
						  </div>
						  <div class="form-group">
							<label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Student Class <span class="required">*</span>
							</label>
							<div class="col-md-6 col-sm-6 col-xs-12">
							  <select name="classs" required class="form-control">
								<option>Select Class </option>
								{% if classes %}
									{% for cls in classes%}
										<option value="{{cls.id}}" {% if cls.id == student.classs %} selected {% endif %}>{{cls.class_name}}</option>
									{% endfor %}
								{% endif %}
							  </select>
							</div>
						  </div>
						
						
						  <div class="ln_solid"></div>
						  <div class="form-group">
							<div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
							  <button type="submit" class="btn btn-success">Update</button>
							  <input type="hidden" name="sid" value="{{student.id}}" />
							</div>
						  </div>

						</form>
					{% endif %}
                  </div>
                </div>
              </div>
            </div>

            
          </div>
        </div>
{% endblock %}

students/templates/students/index.html
{% extends "base.html" %}
{% block content %}
{% load staticfiles %}
{% load classname %}

    <!-- page content -->
        <div class="right_col" role="main">
          <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Students List </h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a aria-expanded="false" role="button" data-toggle="dropdown" class="dropdown-toggle" href="#"><i class="fa fa-wrench"></i></a>
                        <ul role="menu" class="dropdown-menu">
                          <li><a href="#">Settings 1</a>
                          </li>
                          <li><a href="#">Settings 2</a>
                          </li>
                        </ul>
                      </li>
                      <li><a class="close-link"><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>

                  <div class="x_content">

                   

                    <div class="table-responsive">
                      <table class="table table-striped jambo_table bulk_action">
                        <thead>
                          <tr class="headings">
                           
                            <th class="column-title">Student Name </th>
                            <th class="column-title">Class </th>
                            
                            <th class="column-title no-link last"><span class="nobr">Action</span>
                            </th>
                            
                          </tr>
                        </thead>

                        <tbody>
						{% if students %}
							{% for student in students %}
							  <tr class="even pointer">
							   
								<td class=" ">{{ student.name }}</td>
								<td class=" ">{{ student.classs|cut }}</td>
								<td class=" last"><a href="{% url 'students:deletestudent' student.id %}" class="confirmation">Delete</a> | <a href="{% url 'students:editstudent' student.id %}">Edit</a>
								</td>
							  </tr>
						  {% endfor %}
                        {% else %}
							<tr class="even pointer">
							<td colspan="3">No student in List</td>
							</tr>
						{% endif %} 
                        </tbody>
                      </table>
                    </div>
					<div class="col-md-9 pagination">
						<span class="step-links">
							{% if students.has_previous %}
								<a href="?page={{ students.previous_page_number }}">previous</a>
							{% endif %}

							<span class="current">
								Page {{ students.number }} of {{ students.paginator.num_pages }}.
							</span>

							{% if students.has_next %}
								<a href="?page={{ students.next_page_number }}">next</a>
							{% endif %}
						</span>
					</div>
					<div class="col-md-3 right">
					<a href="{% url 'students:addstudent'%}" class="btn btn-success right">Add Student</a>
					</div>
                  </div>
                </div>
              </div>
        </div>
        <!-- /page content -->
{% endblock %}