MyPython/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls import patterns, include, url
from login.views import *

urlpatterns = [
             url(r'^polls/', include('polls.urls')),
             url(r'^students/', include('students.urls')),
             url(r'^teachers/', include('teachers.urls')),
             url(r'^user/', include('login.urls')),
             url(r'^classes/', include('manage_classes.urls')),
             url(r'^admin/', admin.site.urls),
              url(r'^$',home),
              url(r'^logout/$', logout_page),
              url(r'^login/$',  'django.contrib.auth.views.login'),
              url(r'^accounts/login/$',
                  'django.contrib.auth.views.login'),  # If user is not login it will redirect to login page
              url(r'^register/$', register),
              url(r'^register/success/$', register_success),
              url(r'^home/$', home),
]

login/urls.py
from django.conf.urls import url
from . import views
app_name = 'login'
urlpatterns = [
    #url(r'^$',views.changepassword,name='changepassword'),
    #url(r'^(?s<student_id>[0-9]+)/$',views.detail,name="viewstudent"),
    #url(r'^(?P<student_id>[0-9]+)/edit/$',views.edit,name="editstudent"),
	#url(r'^(?P<student_id>[0-9]+)/update/$',views.update,name="updatestudent"),
	#url(r'^(?P<student_id>[0-9]+)/delete/$',views.delete,name="deletestudent"),
    url(r'^changepassword',views.changepassword,name="changepassword"),
    url(r'^changeprofile',views.changeprofile,name="changeprofile"),

]

teachers/urls.py
from django.conf.urls import url
from . import views
app_name = 'teachers'
urlpatterns = [
    url(r'^$',views.index,name='teachers'),
    #url(r'^(?s<student_id>[0-9]+)/$',views.detail,name="viewstudent"),
    url(r'^(?P<teacher_id>[0-9]+)/edit/$',views.edit,name="editteacher"),
	url(r'^(?P<teacher_id>[0-9]+)/update/$',views.update,name="updateteacher"),
	url(r'^(?P<teacher_id>[0-9]+)/delete/$',views.delete,name="deleteteacher"),
    url(r'^add',views.add,name="addteacher"),

]

teachers/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
import  datetime
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils import timezone

# Create your models here.
class Teachers(models.Model):

    name = models.CharField(max_length=200)
    qualification = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    state = models.CharField(max_length=200)
    experience = models.CharField(max_length=200)
    address = models.TextField(max_length=500)
    phone_number = models.CharField(max_length=200)
    add_date = models.DateTimeField('date added')
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    def __str__(self):
        return self.name

teachers/forms.py
import re
from django import forms
from django.utils.translation import ugettext_lazy as _
class addteacherform(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'required': True, 'max_length': 30}),label=_("Teacher Name"))
    qualification = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'required': True, 'max_length': 30}),label=_("Qualification"))
    address = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'required': True, 'max_length': 30}), label=_("Address"))
    city = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'required': True, 'max_length': 30}),label=_("City"))
    state = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'required': True, 'max_length': 30}),label=_("State"))
    phone_number = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'required': True, 'max_length': 30}),label=_("Phone Number"))
    expeirience = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'required': True, 'max_length': 30}),label=_("Experience"))

teachers/views.py
from django.shortcuts import render,get_object_or_404,render_to_response
from django.http import HttpResponse,Http404,HttpResponseRedirect
from django.template import loader
from django.core.urlresolvers import reverse
from .models import Teachers
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.views.decorators.csrf import csrf_protect
from django.template import RequestContext
from teachers.forms import *
from django.utils import timezone
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.models import User

# Create your views here.
@login_required
def index(request):
    current_user  = request.user
    uid = current_user.id
    teacher_list = Teachers.objects.filter(user_id=uid).order_by('-id')
    paginator = Paginator(teacher_list, 30)
    page = request.GET.get('page')


    try:
        teachers = paginator.page(page)
    except PageNotAnInteger:

        teachers = paginator.page(1)
    except EmptyPage:

        students = paginator.page(paginator.num_pages)
    return render(request, 'teachers/index.html', {'teachers':teachers})
def edit(request,teacher_id):
    teacher= get_object_or_404(Teachers, id=teacher_id)
    return render(request, 'teachers/editteacher.html', {'teacher': teacher})
def update(request,teacher_id):
	teacher = get_object_or_404(Teachers, id=teacher_id)
	teacher.name = request.POST['tname']
	teacher.qualification= request.POST['qualification']
	teacher.city= request.POST['city']
	teacher.state= request.POST['state']
	teacher.address= request.POST['address']
	teacher.phone_number= request.POST['phone_number']
	teacher.experience= request.POST['experience']
	teacher.save()

	return HttpResponseRedirect(reverse('teachers:teachers'))
@csrf_protect
def add(request):

    if request.method =='POST':
        form = addteacherform(request.POST)
        variables = RequestContext(request, {'form': form})
        if form.is_valid():


            current_user = request.user
            user = User.objects.get(id=current_user.id)
            teacher = Teachers.objects.create(
            name = form.cleaned_data['name'],
            qualification  =form.cleaned_data['qualification'],
            address  =form.cleaned_data['address'],
            city  =form.cleaned_data['city'],
            state  =form.cleaned_data['state'],
            phone_number  =form.cleaned_data['phone_number'],
            experience  =form.cleaned_data['expeirience'],
			user_id = user.id,
            add_date =timezone.now(),
            )

            return HttpResponseRedirect(reverse('teachers:teachers'))
    else:
        form = addteacherform()
        variables = RequestContext(request,{'form':form})
    return render_to_response('teachers/addteacherform.html',variables)
def delete(request,teacher_id):
	teacher = get_object_or_404(Teachers, id=teacher_id)
	teacher.delete()

	return HttpResponseRedirect(reverse('teachers:teachers'))

teachers/templates/teachers/addteacherform.html
{% extends "base.html" %}


{% block content %}

    <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3>Add Teacher</h3>
              </div>

              <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                  <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                      <button class="btn btn-default" type="button">Go!</button>
                    </span>
                  </div>
                </div>
              </div>
            </div>
            <div class="clearfix"></div>
            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Add teacher </h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                          <li><a href="#">Settings 1</a>
                          </li>
                          <li><a href="#">Settings 2</a>
                          </li>
                        </ul>
                      </li>
                      <li><a class="close-link"><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
					{% if form.errors %}
					<div class="alert alert-danger">
					<p>Your username and password didn't match. Please try again.</p>
					</div>
						
					{% endif %}
                  <div class="x_content">
                    <br />
					
						<form class="form-horizontal form-label-left" method="post" action="{% url 'teachers:addteacher'%}">
						{% csrf_token %}
						<input type="hidden" name="user_id" value="{{ user.id }}">
						  <div class="form-group">
							<label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Teacher Name <span class="required">*</span>
							</label>
							<div class="col-md-6 col-sm-6 col-xs-12">
							  {{ form.name }}
							</div>
						  </div>
						  <div class="form-group">
							<label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name"> Qualification <span class="required">*</span>
							</label>
							<div class="col-md-6 col-sm-6 col-xs-12">
							  {{ form.qualification }}
							</div>
						  </div>
						  <div class="form-group">
							<label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name"> Adress <span class="required">*</span>
							</label>
							<div class="col-md-6 col-sm-6 col-xs-12">
							  {{ form.address }}
							</div>
						  </div>
						  <div class="form-group">
							<label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">City<span class="required">*</span>
							</label>
							<div class="col-md-6 col-sm-6 col-xs-12">
							  {{ form.city }}
							</div>
						  </div>
						  <div class="form-group">
							<label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">State <span class="required">*</span>
							</label>
							<div class="col-md-6 col-sm-6 col-xs-12">
							  {{ form.state }}
							</div>
						  </div>
						  <div class="form-group">
							<label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Phone Number <span class="required">*</span>
							</label>
							<div class="col-md-6 col-sm-6 col-xs-12">
							  {{ form.phone_number }}
							</div>
						  </div>
						  <div class="form-group">
							<label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Experience<span class="required">*</span>
							</label>
							<div class="col-md-6 col-sm-6 col-xs-12">
							  {{ form.expeirience }}
							</div>
						  </div>
						  <div class="ln_solid"></div>
						  <div class="form-group">
							<div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
							  <button type="submit" class="btn btn-success">Add</button>
							  <input type="hidden" name="tid" value="{{teacher.id}}" />
							</div>
						  </div>

						</form>
					
                  </div>
                </div>
              </div>
            </div>

            
          </div>
        </div>
{% endblock %}

teachers/templates/teachers/editteacher.html
{% extends "base.html" %}


{% block content %}

    <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3>Edit Student</h3>
              </div>

              <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                  <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                      <button class="btn btn-default" type="button">Go!</button>
                    </span>
                  </div>
                </div>
              </div>
            </div>
            <div class="clearfix"></div>
            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Edit student </h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                          <li><a href="#">Settings 1</a>
                          </li>
                          <li><a href="#">Settings 2</a>
                          </li>
                        </ul>
                      </li>
                      <li><a class="close-link"><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <br />
					{% if teacher %}
						{% if form.errors %}
							<p>Pls check.</p>
						{% endif %}
						<form class="form-horizontal form-label-left" method="post" action="{% url 'teachers:updateteacher' teacher.id %}">
						{% csrf_token %}
						  <div class="form-group">
							<label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Teacher Name <span class="required">*</span>
							</label>
							<div class="col-md-6 col-sm-6 col-xs-12">
							  <input type="text" id="first-name" required="required" class="form-control col-md-7 col-xs-12" name="tname" value="{{ teacher.name }}">
							</div>
						  </div>
						  <div class="form-group">
							<label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Qualification <span class="required">*</span>
							</label>
							<div class="col-md-6 col-sm-6 col-xs-12">
							  <input type="text" id="last-name" required="required" class="form-control col-md-7 col-xs-12" name="qualification" value="{{ teacher.qualification }}">
							</div>
						  </div>
						  <div class="form-group">
							<label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Adress<span class="required">*</span>
							</label>
							<div class="col-md-6 col-sm-6 col-xs-12">
							  <textarea required="required" class="form-control col-md-7 col-xs-12" name="address" >{{ teacher.address }}</textarea>
							</div>
						  </div>
						  <div class="form-group">
							<label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">City <span class="required">*</span>
							</label>
							<div class="col-md-6 col-sm-6 col-xs-12">
							  <input type="text" id="last-name" required="required" class="form-control col-md-7 col-xs-12" name="city" value="{{ teacher.city }}">
							</div>
						  </div>
						  <div class="form-group">
							<label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">State <span class="required">*</span>
							</label>
							<div class="col-md-6 col-sm-6 col-xs-12">
							  <input type="text" id="last-name" required="required" class="form-control col-md-7 col-xs-12" name="state" value="{{ teacher.state }}">
							</div>
						  </div>
						  <div class="form-group">
							<label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Phone Number <span class="required">*</span>
							</label>
							<div class="col-md-6 col-sm-6 col-xs-12">
							  <input type="text" id="last-name" required="required" class="form-control col-md-7 col-xs-12" name="phone_number" value="{{ teacher.phone_number }}">
							</div>
						  </div>
						  <div class="form-group">
							<label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Expeirience <span class="required">*</span>
							</label>
							<div class="col-md-6 col-sm-6 col-xs-12">
							  <input type="text" id="last-name" required="required" class="form-control col-md-7 col-xs-12" name="experience" value="{{ teacher.experience }}">
							</div>
						  </div>
						  <div class="ln_solid"></div>
						  <div class="form-group">
							<div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
							  <button type="submit" class="btn btn-success">Update</button>
							  <input type="hidden" name="tid" value="{{teacher.id}}" />
							</div>
						  </div>

						</form>
					{% endif %}
                  </div>
                </div>
              </div>
            </div>

            
          </div>
        </div>
{% endblock %}

teachers/templates/teachers/index.html
{% extends "base.html" %}


{% block content %}
{% load staticfiles %}


    <!-- page content -->
        <div class="right_col" role="main">
          <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Teachers List </h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a aria-expanded="false" role="button" data-toggle="dropdown" class="dropdown-toggle" href="#"><i class="fa fa-wrench"></i></a>
                        <ul role="menu" class="dropdown-menu">
                          <li><a href="#">Settings 1</a>
                          </li>
                          <li><a href="#">Settings 2</a>
                          </li>
                        </ul>
                      </li>
                      <li><a class="close-link"><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>

                  <div class="x_content">

                   

                    <div class="table-responsive">
                      <table class="table table-striped jambo_table bulk_action">
                        <thead>
                          <tr class="headings">
                           
                            <th class="column-title">Teacher Name </th>
                            <th class="column-title">Qualification </th>
                            <th class="column-title">City </th>
                            <th class="column-title">State </th>
                            <th class="column-title">Phone Number </th>
                            <th class="column-title">Expeirience </th>
                            <th class="column-title">Address </th>
                            
                            <th class="column-title no-link last"><span class="nobr">Action</span>
                            </th>
                            
                          </tr>
                        </thead>

                        <tbody>
						{% if teachers %}
							{% for teacher in teachers %}
							  <tr class="even pointer">
							   
								<td class=" ">{{ teacher.name }}</td>
								<td class=" ">{{ teacher.qualification }}</td>
								<td class=" ">{{ teacher.city }}</td>
								<td class=" ">{{ teacher.state }}</td>
								<td class=" ">{{ teacher.phone_number }}</td>
								<td class=" ">{{ teacher.experience }}</td>
								<td class=" ">{{ teacher.address }}</td>
								<td class=" last"><a href="{% url 'teachers:deleteteacher' teacher.id %}" class="confirmation">Delete</a> | <a href="{% url 'teachers:editteacher' teacher.id %}">Edit</a>
								</td>
							  </tr>
						  {% endfor %}
                        {% else %}
							<tr class="even pointer">
							<td colspan="3">No teacher in List</td>
							</tr>
						{% endif %} 
                        </tbody>
                      </table>
                    </div>
					<div class="col-md-9 pagination">
						<span class="step-links">
							{% if teachers.has_previous %}
								<a href="?page={{ teachers.previous_page_number }}">previous</a>
							{% endif %}

							<span class="current">
								Page {{ teachers.number }} of {{ teachers.paginator.num_pages }}.
							</span>

							{% if teachers.has_next %}
								<a href="?page={{ teachers.next_page_number }}">next</a>
							{% endif %}
						</span>
					</div>
					<div class="col-md-3 right">
					<a href="{% url 'teachers:addteacher'%}" class="btn btn-success right">Add Teacher</a>
					</div>
                  </div>
                </div>
              </div>
        </div>
        <!-- /page content -->
{% endblock %}